 
services:
  fastapi:
    build: 
        context: .
        dockerfile: build/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/api/"
    command: fastapi run --reload
    