 
services:
  fastapi:
    build: 
        context: .
        dockerfile: build/Dockerfile
    ports:
      - 8000:8000
    env_file: "build/.env"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./:/app/api/"
    